using System;
using System.Runtime.CompilerServices;

namespace Basho.Logging
{
    public interface ILog<T> : ILog { }

    public interface ILog
    {
        void Debug(string message, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void Debug(string message, Exception ex, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void DebugFormat(string format, object arg0, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void DebugFormat(string format, object arg0, object arg1, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void DebugFormat(string format, object arg0, object arg1, object arg2, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void DebugFormat(string format, object arg0, object arg1, object arg2, object arg3, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void DebugFormat(string format, object arg0, object arg1, object arg2, object arg3, object arg4, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void DebugFormat(string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void DebugFormat(string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void DebugFormat(string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);

        void Info(string message, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void Info(string message, Exception ex, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void InfoFormat(string format, object arg0, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void InfoFormat(string format, object arg0, object arg1, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void InfoFormat(string format, object arg0, object arg1, object arg2, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void InfoFormat(string format, object arg0, object arg1, object arg2, object arg3, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void InfoFormat(string format, object arg0, object arg1, object arg2, object arg3, object arg4, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void InfoFormat(string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void InfoFormat(string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void InfoFormat(string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);

        void Warn(string message, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void Warn(string message, Exception ex, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void WarnFormat(string format, object arg0, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void WarnFormat(string format, object arg0, object arg1, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void WarnFormat(string format, object arg0, object arg1, object arg2, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void WarnFormat(string format, object arg0, object arg1, object arg2, object arg3, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void WarnFormat(string format, object arg0, object arg1, object arg2, object arg3, object arg4, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void WarnFormat(string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void WarnFormat(string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void WarnFormat(string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);

        void Error(string message, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void Error(string message, Exception ex, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void ErrorFormat(string format, object arg0, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void ErrorFormat(string format, object arg0, object arg1, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void ErrorFormat(string format, object arg0, object arg1, object arg2, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void ErrorFormat(string format, object arg0, object arg1, object arg2, object arg3, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void ErrorFormat(string format, object arg0, object arg1, object arg2, object arg3, object arg4, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void ErrorFormat(string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void ErrorFormat(string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void ErrorFormat(string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);

        void Fatal(string message, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void Fatal(string message, Exception ex, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void FatalFormat(string format, object arg0, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void FatalFormat(string format, object arg0, object arg1, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void FatalFormat(string format, object arg0, object arg1, object arg2, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void FatalFormat(string format, object arg0, object arg1, object arg2, object arg3, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void FatalFormat(string format, object arg0, object arg1, object arg2, object arg3, object arg4, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void FatalFormat(string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void FatalFormat(string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
        void FatalFormat(string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7, LogFormatStyle style = LogFormatStyle.Normal, [CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0);
    }
}
